socks/app/core/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from core.views import *
from django.contrib.auth.views import login, logout


urlpatterns = patterns('',
    # Task
    url(r'^$', login_required(JournalPage.as_view())),
    url(r'^list', login_required(result), name='result'),
    url(r'^search', login_required(search), name='search'),
    url(r'^result/(?P<ids>.*)/(?P<id>.*)/', login_required(search_obj), name='search_obj'),
    url(r'^result/(?P<id>.*)/', login_required(search_obj_country), name='search_obj_country'),
    url(r'^host/(?P<id>.*)/', login_required(host_view), name='host_view'),
    url(r'^profile/(?P<username>.*)/', login_required(profile), name='profile'),
    url(r'^password', login_required(edit_password), name='edit_password'),
    url(r'^tarif', login_required(choice_tarif), name='choice_tarif'),

    url(r'^audit/(?P<id>.*)/', login_required(audits_socks), name='audits_socks'),

    url(r'^accounts/login/$',  login_view, name='login_view'),
    url(r'^accounts/logout/$', logout_view, name='logout_view'),

    url(r'^registration$', registration, name='registration'),

)

socks/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^', include('core.urls')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

socks/app/core/models.py
# -*- coding: utf-8 -*-
from datetime import timedelta, datetime, date
import re
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils import timezone


class Tariff(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    limit = models.IntegerField( blank=True, null=True)
    price = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        verbose_name = u"Тариф"
        verbose_name_plural = u'Тарифы'

    def __unicode__(self):
        return unicode(self.name)

ACCOUNT_ACTIVE = 1
ACCOUNT_SUSPENDED = 0

STATUS_ENABLE = 1
STATUS_DISABLE = 2

ACCOUNT_CHOICES = (
    (ACCOUNT_SUSPENDED, 'suspended'),
    (ACCOUNT_ACTIVE, 'active'),
)


STATUS_CHOICES = (
    (STATUS_ENABLE, 'NO'),
    (STATUS_DISABLE, 'YES')
)






class SocksList(models.Model):
    hostname = models.CharField(max_length=255, blank=True, null=True)
    ip = models.CharField(max_length=555)
    port = models.IntegerField(blank=True, null=True)

    country = models.CharField(max_length=255, blank=True, null=True)
    country_in = models.CharField(max_length=255, blank=True, null=True)#Сокращенное название страны
    city = models.CharField(max_length=255, blank=True, null=True)
    state = models.CharField(max_length=255, blank=True, null=True)
    need_recheck = models.BooleanField(default=True)

    uptime = models.DateTimeField(blank=True, null=True)
    last_check = models.DateTimeField(blank=True, null=True)
    speed = models.CharField(max_length=255, blank=True, null=True, default=0)

    def __unicode__(self):
        return unicode(self.hostname)

    def uptime_beta(self):
        res = str(datetime.now(timezone.utc) - self.uptime)
        return res[0:-7]

    class Meta:
        verbose_name = u"Список соксов"
        verbose_name_plural = u'Список соксов'

class CoreUser(models.Model):
    user = models.OneToOneField(User, related_name='core_user')
    icq = models.IntegerField(max_length=20, blank=True, null=True)
    jabber = models.CharField(max_length=200, blank=True, null=True)
    account = models.IntegerField(choices=ACCOUNT_CHOICES, default=ACCOUNT_ACTIVE, blank=True, null=True)
    vip_status = models.IntegerField(choices=STATUS_CHOICES, default=STATUS_ENABLE, blank=True, null=True)
    proxy_list_size = models.IntegerField(max_length=1000, blank=True, null=True,default=25)
    unused_proxies = models.IntegerField(blank=True, null=True)
    opt_till = models.DateTimeField(default=timezone.now,blank=True, null=True)#дата платежа

    tariff = models.ForeignKey(Tariff, related_name='user_tarif', blank=True)
    new_tariff = models.ForeignKey(Tariff, related_name='user_new_tarif', blank=True, null=True)

    used = models.ManyToManyField(SocksList, related_name='user_used', blank=True, null=True)

    balance = models.IntegerField(blank=True, null=True)

    class Meta:
        verbose_name = u"Пользователь"
        verbose_name_plural = u'Пользователи'

    def __unicode__(self):
        return unicode(self.user.username)

    # def save(self, *args, **kwargs):
    #     self.code = _createHash()
    #     super(JournalUser, self).save()

    def first_name(self):
        return self.user.first_name

    def last_name(self):
        return self.user.last_name

    def email(self):
        return self.user.email

    def paid_till(self):
        return self.opt_till + timedelta(30)

    def residue(self):
        p = re.sub("^\s+|[*]|[$]|[€]|\n|\r|\s+$", '', self.tariff.price)
        return self.balance - int(p)

socks/app/core/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.forms import *
from django import forms
from core.models import CoreUser


class CoreUserForm(forms.ModelForm):
    username = forms.CharField(max_length=20, label=u'username')
    email = forms.EmailField(max_length=100, label=u'Email')
    password = forms.CharField(max_length=12, label=u'password')
    icq = forms.CharField(max_length=9, label=u'ICQ', required=False)
    jabber = forms.CharField(label=u'Jabber', required=False)

    class Meta:
        model = CoreUser
        exclude = ['user', 'account', 'vip_status', 'proxy_list_size', 'unused_proxies', 'opt_till', 'balance']

    def clean_email(self):
        email = self.cleaned_data.get('email')

        try:
            current_email = self.instance.user.user.email
            if current_email == email:
                return email
        except:
            pass

        if email and User.objects.filter(email=email).count():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def __init__(self, *args, **kwargs):
        super(CoreUserForm, self).__init__(*args, **kwargs)

        for field in self.base_fields:
            label = self.fields[field].label
        self.fields['username'].widget.attrs['placeholder'] = 'Username'
        self.fields['email'].widget.attrs['placeholder'] = 'Email'
        self.fields['jabber'].widget.attrs['placeholder'] = 'Jabber'
        self.fields['icq'].widget.attrs['placeholder'] = 'ICQ'
        self.fields['password'].widget.attrs['placeholder'] = 'Password'

socks/app/core/views.py
from datetime import timedelta, datetime, date
import re
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import AnonymousUser
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django .db.models import Q
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.views.generic.base import TemplateView
from core.forms import CoreUserForm
from core.models import *
from socks.settings import FETCH_TIMEOUT


class JournalPage(TemplateView):
    template_name = "search.html"

    def get_context_data(self, **kwargs):
        context = super(JournalPage, self).get_context_data(**kwargs)
        news = 'test'
        context['socks'] = SocksList.objects.filter(need_recheck=True).order_by('country')
        context['socks_count'] = SocksList.objects.filter(need_recheck=True).count()
        user = self.request.user
        smena(user)
        core_user = CoreUser.objects.get(user=user)
        paid_till = core_user.paid_till()
        context['paid_till'] = paid_till
        if self.request.user.is_authenticated():
            context['name'] = self.request.user.username
        return context

    def dispatch(self, *args, **kwargs):
        return super(JournalPage, self).dispatch(*args, **kwargs)

def smena(user):
    core_user = CoreUser.objects.get(user=user)
    if core_user.paid_till() == date.today():
            core_user.tariff = core_user.new_tariff
            tar = Tariff.objects.get(name=core_user.tariff.name)
            core_user.unused_proxies = tar.limit
            core_user.save()

def result(request):
    context = RequestContext(request)
    user = request.user
    context['user'] = CoreUser.objects.get(user=user)
    if request.POST:
        country_s = request.POST.getlist('country')
        city_s = request.POST.getlist('city')
        city_un = request.POST.getlist('city_un')
        request.session['country_s'] = country_s
        request.session['city_s'] = city_s
        request.session['city_un'] = city_un

        socks_list = None

        socks_list_city_un = []
        if city_s != '':
          if city_un != '':
             for t in city_un:
               try:
                  hs = SocksList.objects.get(Q(country__icontains=str(t.split(',')[0]), city__icontains=str(t.split(',')[1])))
                  socks_list_city_un.append(hs.id)
               except:
                  iu = SocksList.objects.filter(Q(country__icontains=str(t.split(',')[0]), city__icontains=str(t.split(',')[1])))
                  for ss in iu:
                    socks_list_city_un.append(ss.id)
        else:
            pass


        socks_list_city = []
        if city_s != '':
          for t in city_s:
             try:
                hs = SocksList.objects.get(Q(city__icontains=str(t)))
                socks_list_city.append(hs.id)
             except:
                iu = SocksList.objects.filter(Q(city__icontains=str(t)))
                for ss in iu:
                    socks_list_city.append(ss.id)


        socks_list_country = []
        if country_s != '':
          for t in country_s:
             try:
                hs = SocksList.objects.get(Q(country__icontains=str(t)))
                socks_list_country.append(hs.id)
             except:
                iu = SocksList.objects.filter(Q(country__icontains=str(t)))
                for ss in iu:
                    socks_list_country.append(ss.id)

        socks_list = SocksList.objects.filter(need_recheck=True).filter(Q(id__in=socks_list_city_un) |
                                            Q(id__in=socks_list_city) |
                                            Q(id__in=socks_list_country)
                                            ).order_by('country')

        paginator = Paginator(socks_list, CoreUser.objects.get(user=user).proxy_list_size) # Show 25 contacts per page

        page = request.GET.get('page')
        try:
           socks = paginator.page(page)
        except PageNotAnInteger:
           socks  = paginator.page(1)
        except EmptyPage:
           socks = paginator.page(paginator.num_pages)
        context['socks'] = socks
        context['name'] = request.user.username
        context['socks_count'] = SocksList.objects.filter(need_recheck=True).count()
    else:
        country_s = ''
        if request.POST.getlist('country_s'):
            country_s = request.session['country_s']
        city_s = ''
        if request.POST.getlist('city'):
           city_s = request.session['city_s']
        city_un = ''
        if request.POST.getlist('city_un'):
           city_un = request.session['city_un']
        socks_list = None

        socks_list_city_un = []
        if city_s != '':
          if city_un != '':
             for t in city_un:
               try:
                  hs = SocksList.objects.get(Q(country__icontains=str(t.split(',')[0]), city__icontains=str(t.split(',')[1])))
                  socks_list_city_un.append(hs.id)
               except:
                  iu = SocksList.objects.filter(Q(country__icontains=str(t.split(',')[0]), city__icontains=str(t.split(',')[1])))
                  for ss in iu:
                    socks_list_city_un.append(ss.id)
        else:
            pass


        socks_list_city = []
        if city_s != '':
          for t in city_s:
             try:
                hs = SocksList.objects.get(Q(city__icontains=str(t)))
                socks_list_city.append(hs.id)
             except:
                iu = SocksList.objects.filter(Q(city__icontains=str(t)))
                for ss in iu:
                    socks_list_city.append(ss.id)


        socks_list_country = []
        if country_s != '':
          for t in country_s:
             try:
                hs = SocksList.objects.get(Q(country__icontains=str(t)))
                socks_list_country.append(hs.id)
             except:
                iu = SocksList.objects.filter(Q(country__icontains=str(t)))
                for ss in iu:
                    socks_list_country.append(ss.id)

        socks_list = SocksList.objects.filter(need_recheck=True).filter(Q(id__in=socks_list_city_un) |
                                            Q(id__in=socks_list_city) |
                                            Q(id__in=socks_list_country)
                                            ).order_by('country')

        paginator = Paginator(socks_list, CoreUser.objects.get(user=user).proxy_list_size)  # Show 25 contacts per page

        page = request.GET.get('page')
        try:
           socks = paginator.page(page)
        except PageNotAnInteger:
           socks  = paginator.page(1)
        except EmptyPage:
           socks = paginator.page(paginator.num_pages)
        context['socks'] = socks
        context['name'] = request.user.username
        context['socks_count'] = SocksList.objects.filter(need_recheck=True).count()
    return render_to_response('result-search.html', context)

def search(request):
    context = RequestContext(request)
    user = request.user
    context['user'] = CoreUser.objects.get(user=user)

    if request.POST:
      try:
        country_s = request.POST.get('country')
        city_s = request.POST.get('city')
        host_s = request.POST.get('host')
        ip = request.POST.get('ip')
        request.session['country_s'] = country_s
        request.session['city_s'] = city_s
        request.session['ip'] = ip
        request.session['host_s'] = host_s
        socks_list_host = []
        if host_s != '':
            for h in host_s.split(','):
              p = re.sub("^\s+|[*]|\n|\r|\s+$", '', h)
              if p != '':
               try:
                   hs = SocksList.objects.get(Q(hostname__icontains=p))
                   socks_list_host.append(hs.id)
               except:
                   iu = SocksList.objects.filter(Q(hostname__icontains=p))
                   for ss in iu:
                       socks_list_host.append(ss.id)
              else:
                  pass

        socks_list_ip = []
        if ip != '':
            for i in ip.split(','):
              p = re.sub("^\s+|[*]|\n|\r|\s+$", '', i)
              if p != '':
                try:
                   iu = SocksList.objects.get(Q(ip__icontains=p))
                   socks_list_ip.append(iu.id)
                except:
                   iu = SocksList.objects.filter(Q(ip__icontains=p))
                   for ss in iu:
                       socks_list_ip.append(ss.id)
              else:
                pass
        socks_list_coun = []
        if country_s != '':
            for i in country_s.split(','):
              p = re.sub("^\s+|[*]|\n|\r|\s+$", '', i)
              if p != '':
                try:
                   iu = SocksList.objects.get(Q(country__icontains=p))
                   socks_list_coun.append(iu.id)
                except:
                   iu = SocksList.objects.filter(Q(country__icontains=p))
                   for ss in iu:
                       socks_list_coun.append(ss.id)
              else:
                pass
        socks_list_city = []
        if city_s != '':
            for i in city_s.split(','):
              p = re.sub("^\s+|[*]|\n|\r|\s+$", '', i)
              if p != '':
                try:
                   iu = SocksList.objects.get(Q(city__icontains=p))
                   socks_list_city.append(iu.id)
                except:
                   iu = SocksList.objects.filter(Q(city__icontains=p))
                   for ss in iu:
                      socks_list_city.append(ss.id)
              else:
                pass


        socks_list = SocksList.objects.filter(need_recheck=True).filter(Q(id__in=socks_list_coun) |
                                            Q(id__in=socks_list_city)|

socks/app/core/templates/audits-error.html
<html>
<head>
    <title> {{ sock.hostname }}</title>
    <link href="{{ STATIC_URL }}/css/style.css" rel="stylesheet">
</head>
<body   style="margin: -1px;overflow: hidden;">
<div class="audits_popup"><br>
    <br><br>
    <h2>Unable to check this socks, try another one... </h2><br>
    <a onclick="window.close()" href="#">Close</a>

</div>
</body></html>

socks/app/core/templates/audits.html
<html>
<head>
    <title> {{ sock.hostname }}</title>
    <link href="{{ STATIC_URL }}/css/style.css" rel="stylesheet">
</head>
<body   style="margin: -1px;overflow: hidden;">
<div class="audits_popup"><br>
    <h2>Checking proxy...done</h2>
    <h2>Operation get proxy #{{ sock.id }}:{{ sock.country_in }}</h2>
    <h2>completed</h2><br>
    <h2>{{ sock.hostname }}</h2>
    <h2>Proxy IP:PORT: <span>{{ sock.ip }}:{{ sock.port }}</span></h2>
    <h4>SORBS blacklist:no</h4>
    <a onclick="window.close()" href="#">Close</a>

</div>
</body></html>

socks/app/core/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>test</title>
    <link href="{{ STATIC_URL }}/css/style.css" rel="stylesheet">
</head>
<body>
<div class="content">

  {% block menu %}
     {% include 'menu.html' %}
  {% endblock %}

  {% block profile %}
  {% endblock %}

  {% block search %}
  {% endblock %}
  {% block search_text %}
  {% endblock %}

  {% block content %}
  {% endblock %}
</div>
<div class="footer">
    <p>© 2004-2014 <a href="/">admin.example.com</a> | ICQ: 777888999 | E-mail: <a href="mailto:admin@example.com">admin@example.com</a> </p>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{{ STATIC_URL }}js/custom.js"></script>
<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');
</script>
</body>
</html>

socks/app/core/templates/choise_tarif.html
{% load core_extras %}
<html>
<head>
    <title> {{ core_user.tariff }}</title>
    <link href="{{ STATIC_URL }}/css/style.css" rel="stylesheet">
</head>
<body style="margin: -1px;overflow: hidden;">
<form class="form-horizontal" action="{{  request.get_full_path }}" role="form" method="POST" data-submit="password">{% csrf_token %}
<div style="text-align: center;margin-top: 20px">

{% if success %}
Thank you! The rate will be changed during the next date of debiting
{% else %}
{% for tarif in tariff %}

    <div class="tarif">{{ tarif.name }}<br>
    {% if tarif.name == 'unlim' %}∞{% else %}{{ tarif.limit }}{% endif %}<br>
    {{ tarif.price }}<br>
    <input type="radio" name="tarif" value="{{ tarif.id }}">
    </div>

{% endfor %}

<p><button type="submit" >[SAVE]</button></p>
{% endif %}
{% if errors %}
   Error
{% endif %}

{% if similar %}
This tariff you have already activated
{% endif %}
<br>
<a onclick="window.close()" href="#">Close</a>
</div>
</form>
</body></html>

socks/app/core/templates/host-view.html
{% load core_extras %}
<html>
<head>
    <title> {{ sock.hostname }}</title>
    <link href="{{ STATIC_URL }}/css/style.css" rel="stylesheet">
</head>
<body style="margin: -1px;overflow: hidden;">
<table style="width: 100%" class="proxytbl" cellspacing="1">
  <tbody>
  <tr valign="center" align="right">
      <th></th>
      <th>proxy details</th>
  </tr>
  </tbody>
    <tbody>

    <tr class="tr_popup t_cycleodd">
        <td class="t_host_popup">
            <b>Host:</b>
        </td>
        <td class="t_hostname_popup">
           {{ sock.hostname|edit_host }}
        </td>
    </tr>
    <tr class="tr_popup t_cycleeven">
        <td class="t_status_popup">
           <b>Status:</b>
        </td>
        <td class="t_state">
            Online
        </td>
    </tr>
    <tr class="tr_popup t_cycleodd">
        <td class="t_country_popup">
           <b>Country:</b>
        </td>
        <td class="t_state">
            [{{ sock.country_in }}]{{ sock.country }}
        </td>
    </tr>
    <tr class="tr_popup t_cycleeven">
        <td class="t_city_popup">
           <b>City:</b>
        </td>
        <td class="t_state">
            {{ sock.city }}
        </td>
    </tr>
   <!-- <tr class="tr_popup t_cycleodd">
        <td class="t_state_popup">
           <b>State:</b>
        </td>
        <td class="t_state">
            {{ sock.state }}
        </td>
    </tr>-->
    <tr class="tr_popup t_cycleeven">
        <td class="t_speed_popup">
           <b>Speed:</b>
        </td>
        <td class="t_state">
            {{ sock.speed }}
        </td>
    </tr>
    <tr class="tr_popup t_cycleodd">
        <td class="t_uptime_popup">
           <b>Uptime:</b>
        </td>
        <td class="t_state">
            {{ sock.uptime_beta }}
        </td>
    </tr>
    <tr class="tr_popup t_cycleeven">
        <td class="t_port_popup">
           <b>IP:PORT</b>
        </td>
        <td class="t_state">
            {% if core.unused_proxies == 0 %}
                NO
            {% else %}
            <a  class="click_here" href="{% url "audits_socks" sock.id  %}">click here to view</a>
            {% endif %}
        </td>
    </tr>
    <tr class="tr_popup t_cycleodd">
        <td class="t_id_popup">
           Proxy ID:
        </td>
        <td class="t_state">
            #{{ sock.id }}
        </td>
    </tr>
    <tr align="center">
      <td colspan="2" style="background: #4e86b5;"><a onclick="window.close()" href="#">Close</a></td>
    </tr>
</tbody>



  </table>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{{ STATIC_URL }}js/custom.js"></script>
</body></html>

socks/app/core/templates/menu.html
<div class="header">
   <a href="/">HOME</a> | <a href="{% url "profile"  name  %}">Account Settings</a> | <a href="/accounts/logout/">[logout]</a>
</div>
<div class="menu">
    <div class="menu_left">
        <p>Hello <b>{{ name }}</b>!</p>
        <p style="font-size: 12px;">There are {{ socks_count }} proxies online at this time</p>
    </div>
    <div class="menu_right">
      <p>Date: {% now "j/n/Y H:i:s" %}</p>
      <p>Next pay date: {{ paid_till|date:"j/n/Y H:i:s" }}{{ user.paid_till|date:"j/n/Y H:i:s" }}</p>
    </div>
</div>

socks/app/core/templates/profile.html
{% extends 'base.html' %}
{% block profile %}
<table style="width: 100%" class="proxytbl" cellspacing="1">
  <tbody>
  <tr align="center">
      <td colspan="2" style="background: #4e86b5;">Account {{ user.user.username }} settings</td>
    </tr>
  </tbody>
    <tbody>

    <tr class="tr_popup t_cycleodd">
        <td class="t_host_popup">
            <b>Email:</b>
        </td>
        <td class="t_hostname_popup">
           {{ user.email }}
        </td>
    </tr>
    {% if user.icq == 0 %}
    {% else %}
    <tr class="tr_popup t_cycleeven">
        <td class="t_status_popup">
           <b>ICQ:</b>
        </td>
        <td class="t_state">
            {{ user.icq }}
        </td>
    </tr>
    {% endif %}
    {% if user.jabber == '0' %}
    {% else %}
    <tr class="tr_popup t_cycleodd">
        <td class="t_country_popup">
           <b>Jabber:</b>
        </td>
        <td class="t_state">
           {{ user.jabber }}
        </td>
    </tr>
    {% endif %}

    <tr class="tr_popup t_cycleeven">
        <td class="t_city_popup">
           <b>Password:</b>
        </td>
        <td class="t_state">
            [<a onclick="window.open('{% url 'edit_password' %}','','resizable=yes,status=0,toolbar=0,menubar=0,width=350,height=250,left=500,top='+(screen.availHeight/2-365)+'');return false;" href="{%   url 'edit_password' %}">click here to change</a>]
        </td>
    </tr>
    <tr class="tr_popup t_cycleodd">
        <td class="t_state_popup">
           <b>Account created:</b>
        </td>
        <td class="t_state">
            {{ user.user.date_joined|date:"j/n/Y H:i:s" }}
        </td>
    </tr>

    <tr align="center">
      <td colspan="2" style="background: #4e86b5;"></td>
    </tr>

    <tr class="tr_popup t_cycleeven">
        <td class="t_speed_popup">
           <b>Account:</b>
        </td>
        <td class="t_state">
            {{ user.get_account_display }}
        </td>
    </tr>
    <tr class="tr_popup t_cycleodd">
        <td class="t_uptime_popup">
           <b>Unused proxies:</b>
        </td>
        <td class="t_state">
            {% if user.tariff.name == 'unlim' %}∞{% else %}{{ user.unused_proxies }}{% endif %}

        </td>
    </tr>
    {% if user.balance != 'None' %}
        <tr class="tr_popup t_cycleeven">
        <td class="t_port_popup">
           <b>Remaining balance:</b>
        </td>
        <td class="t_state">
            {{ user.balance }}$
        </td>
    </tr>
    {% else %}

    {% endif %}
    <tr class="tr_popup t_cycleeven">
        <td class="t_port_popup">
           <b>Paid till:</b>
        </td>
        <td class="t_state">
            {{ user.paid_till|date:"j/n/Y H:i:s" }}
        </td>
    </tr>

    <tr align="center">
      <td colspan="2" style="background: #4e86b5;"></td>
    </tr>

    <tr class="tr_popup t_cycleodd">
        <td class="t_id_popup">
           Tariff:
        </td>
        <td class="t_state">
            {{ user.tariff }} [<a onclick="window.open('{% url 'choice_tarif' %}','','resizable=yes,status=0,toolbar=0,menubar=0,width=350,height=250,left=500,top='+(screen.availHeight/2-365)+'');return false;" href="{%   url 'choice_tarif' %}">Change</a>]
        </td>
    </tr>
    <tr align="center">
      <td colspan="2" style="background: #4e86b5;">© 2004-2014</td>
    </tr>
</tbody>
  </table>
<form class="form-horizontal" action="{{  request.get_full_path }}" role="form" method="POST" data-submit="classesGroupFormSubmit">{% csrf_token %}
<table style="width: 100%" class="proxytbl" cellspacing="1">
  <tbody>
  <tr align="center">
      <td colspan="2" style="background: #4e86b5;">Interface settings</td>
  </tr>
  </tbody>
    <tbody>

    <tr class="tr_popup t_cycleodd">
        <td class="t_host_popup" style="width: 392px;">
            <b>Proxy list size:</b>
        </td>
        <td class="t_hostname_popup">
           <input type="text" value="{{ user.proxy_list_size }}" name="list_size"> lines per page
        </td>
    </tr>
    <tr align="right">
      <td colspan="2" style="background: #4e86b5;"><button type="submit" class="t_submit">[save]</button></td>
    </tr>
</tbody>
  </table></form>

{% endblock %}